<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class StudentsAdmitted extends Model
{
    use HasFactory;

    protected $fillable = [
        'enrollment_id',
        'fullname',
        'image',
        'last_name',
        'middle_name',
        'first_name',
        'prefix',
        'email',
        'date_of_birth',
        'place_of_birth',
        'religion',
        'nationality',
        'gender',
        'civil_status',
        'dialect',
        'contact_number',
        'complete_address',
        'fathers_fullname',
        'fathers_occupation',
        'mothers_fullname',
        'mothers_occupation',
        'parents_address',
        'parents_contact_number',
        'guardian_fullname',
        'guardian_address',
        'employer_details',
        'primary_school',
        'secondary_school',
        'junior_highschool',
        'senior_highschool',
        'last_school_attended',
        'lastschool_name',
        'lastschool_address',
        'course_id',
        'currirulum_id',
        'student_type',
        'year_level',
        'form_138',
        'transcript_of_record',
        'honorable_dismissal',
        'birth_certificate',
        'ncae_copt',
        'good_moral',
        'true_copy_of_grades',
        'police_clearance',
        'student_id',
        'status',
    ];
    public static $rules = [
        'enrollment_id' => 'nullable',
        'fullname' => 'unique:student_applicants,fullname',
        'image' => 'nullable|max:4000|image',
        'last_name' => 'required',
        'middle_name' => 'required',
        'first_name' => 'required',
        'prefix' => 'nullable',
        'email' => 'required|email|max:255|unique:student_applicants,email',
        'date_of_birth' => 'required',
        'place_of_birth' => 'required',
        'religion' => 'required',
        'nationality' => 'required',
        'gender' => 'required',
        'civil_status' => 'required',
        'dialect' => 'required',
        'contact_number' => 'required',
        'complete_address' => 'required',
        'fathers_fullname' => 'required',
        'fathers_occupation' => 'required',
        'mothers_fullname' => 'required',
        'mothers_occupation' => 'required',
        'parents_address' => 'required',
        'parents_contact_number' => 'required',
        'guardian_fullname' => 'nullable',
        'guardian_address' => 'nullable',
        'employer_details' => 'nullable',
        'primary_school' => 'required',
        'secondary_school' => 'required',
        'junior_highschool' => 'required',
        'senior_highschool' => 'required',
        'last_school_attended' => 'nullable',
        'lastschool_name' => 'nullable',
        'lastschool_address' => 'nullable',
        'course_id' => 'required',
        'currirulum_id' => 'nullable|integer',
        'student_type' => 'required',
        'year_level' => 'required',
        'form_138' => 'nullable',
        'transcript_of_record' => 'nullable',
        'honorable_dismissal' => 'nullable',
        'birth_certificate' => 'nullable',
        'ncae_copt' => 'nullable',
        'good_moral' => 'nullable',
        'true_copy_of_grades' => 'nullable',
        'police_clearance' => 'nullable',
        'student_id' => 'nullable',
        'status' => 'nullable',
    ];

    public function course()
    {
        return $this->belongsTo(Course::class);
    }
}
